services:
  - type: web
    name: managerapi
    env: docker
    repo: https://github.com/AngelMeRe/ManagerAPI
    branch: master
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CONNECTION_STRING
        sync: false